from fastapi import APIRouter, Depends, HTTPException
from motor.motor_asyncio import AsyncIOMotorDatabase
from app.api.dependencies import get_current_active_user
from app.core import security
from app.db.mongo import get_database
from app.schemas.user import UserCreate, UserOut, UserInDB

router = APIRouter()

@router.post("/", response_model=UserOut)
async def create_user(
    user: UserCreate,
    db: AsyncIOMotorDatabase = Depends(get_database)
):
    # Normalize inputs
    email = user.email.lower().strip()
    username = user.username.lower().strip()
    
    existing_email = await db.users.find_one({"email": email})
    if existing_email:
        raise HTTPException(status_code=400, detail="Email already registered")

    existing_username = await db.users.find_one({"username": username})
    if existing_username:
        raise HTTPException(status_code=400, detail="Username already taken")
    
    hashed_password = security.get_password_hash(user.password)
    # Create UserInDB instance to validate and prepare data
    user_in_db = UserInDB(
        full_name=user.full_name,
        username=username,
        email=email,
        hashed_password=hashed_password
    )
    
    # Insert into MongoDB
    # exclude id because it will be generated by MongoDB
    user_data = user_in_db.model_dump(by_alias=True, exclude={"id"})
    result = await db.users.insert_one(user_data)
    
    # Fetch the created user
    created_user_doc = await db.users.find_one({"_id": result.inserted_id})
    
    return UserInDB(**created_user_doc)

@router.get("/me", response_model=UserOut)
async def read_users_me(current_user: UserInDB = Depends(get_current_active_user)):
    return current_user
